### ISSUE TITLE
1.0.1 Release Checklist

### ISSUE THREAD

**Issue by glennblock** [splunk/splunk-sdk-php#29]
# Splunk PHP SDK Release Instructions

These are instructions on the various steps necessary to cut out a new
release of the Splunk PHP SDK. Even though the instructions are public,
these steps are only meant to be taken by the SDK maintainers.
### Prerequisites
- [ ] Read through all of these release instructions.
  - Update if necessary. (For example, the version numbers will need updating.)
  - For updates that could apply to other SDKs as well, update the release instructions page for every other SDK.
- [ ] Update changelog.
- [ ] Run test suite on full test matrix.
- [ ] Run all examples.
- [ ] Run all dev.splunk.com code samples.
- [ ] Remove old temporary branches. This includes feature branches, old release branches, and most branches that have been merged to develop.
  - (Exception: The "promises-old" branch in the JavaScript SDK should be retained for the time being.)
### Release Steps
- [ ] Create release branch off of develop (`release/1.0.1`).
  - `git checkout develop`
  - `git pull`
  - `git checkout -b release/1.0.1`
- [ ] <strike>Update the version number:</strike>
  - _No version number currently exists in PHP SDK source code._
- [ ] <strike>Make sure the version number change didn't break anything:</strike>
  - _No version number currently exists in PHP SDK source code._
- [ ] Merge to `master` locally. Ensure the commit message is "Release 1.0.1".
  - `git checkout master`
  - `git merge --no-ff -m "Release 1.0.1" release/1.0.1`
  - `git commit`
- [ ] Tag the above commit as `1.0.1`.
  - `git tag 1.0.1`
- [ ] Push the `master` and the `1.0.1` tag to GitHub.
  - `git push origin master`
  - `git push --tags`
- [ ] Delete the release branch:
  - `git push origin :release/1.0.1`
  - `git branch -d release/1.0.1`
- [ ] Sanity check that released version works:
  - In a clean VM, pull the latest SDK from master.
  - Run these existing UI examples:
    - List Saved Searches
    - List Jobs
- [ ] Verify with Docs team that:
  - Readme is ready. For point releases, the version number needs to be updated at a minimum.
  - Changelog is ready, includes a list of changes for the current version.
  - Dev Portal updates are ready to be pushed. For point releases, the "What's new" page needs to be updated at a minimum.
  - The API Reference (docs.splunk.com/Documentation/SDK) is ready to be published.
- [ ] Hand off to marketing to announce. See next section.
### Announce!

Hurrah, the new release is basically done! You can now announce it on the
following channels:
- Twitter (@splunkdev, maybe @splunk)
- Google Groups (splunkdev)
- Dev Portal (http://dev.splunk.com)
- Dev Blog (http://blogs.splunk.com/dev)
